### ISSUE TITLE
SqlMagic.displaylimit not working with autopandas option

### ISSUE THREAD

**Issue by kienerj** [catherinedevlin/ipython-sql#51]
I set

%config SqlMagic.displaylimit=5 

but when running a select statement all rows are displayed.

Python 2.7 on Windows 64-bit.

When doing %config SqlMagic

The correct value of 5 is shown:

SqlMagic.displaylimit=<Int>
    Current: 5
    Automatically limit the number of rows displayed (full result set is still
    stored)

**Comment by kienerj** [comment]
OK. My bad. This happened becasue I set 2 options in 1 cell. that does not work. With 1 option per cell it works fine.

**Comment by kienerj** [comment]
It seems that if autopandas is set, then the displaylimit is ignored!

**Comment by n-s-f** [comment]
@kienerj 

That is because when autopandas is set, the result in convereted into a DataFrame, and so it's the dataframe that's printed, not the result set.

You can see that in this code base [here](https://github.com/catherinedevlin/ipython-sql/blob/26af5528cd7957a638e9691b95b5a25bc7d50fc1/src/sql/run.py#L108-L110).

To fix this you can set the display options on pandas itself, e.g.:

```.py
import pandas as pd
pd.set_option('max_rows', 10)
```

See [here](http://pandas.pydata.org/pandas-docs/version/0.18.1/options.html#frequently-used-options) for more details.

That will solve your immediate problem. 

To fix this problem in a more permanent way, you can go into the code I referenced above, store the value of `max_rows` in a variable, set the `max_rows` option to the `displaylimit` config value, print the dataframe, then reset the `max_rows` option on pandas to whatever it was before.

**Comment by n-s-f** [comment]
@kienerj I just spent a while looking into it - the way the code is set up (possibly the way all ipython magic has to happen, I don't know) it doesn't seem possible to execute any code after the block has run.

Therefore it's not possible to reset the pandas `max_rows` option after the block has executed.

I think changing the pandas `max_rows` option without changing it back is unacceptable, because in that case setting `displaylimit` on SQL magic would mysteriously change all of pandas' behavior elsewhere as well.

Therefore I suggest allowing the user to manually handle the pandas max_rows option.

I will put a note in the readme about this and submit a pull request.

**Comment by catherinedevlin** [comment]
Thanks to n-s-f, I think that his documentation fix is the best resolution we can get on this.  Pandas has its own system for a DataFrame, and having our `displaylimit` implicitly mess with that doesn't seem like a good idea; we'll settle with documenting it.  Also remember that a `DataFrame` has a `head` method that accepts a number of rows as an argument: http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.head.html
